# Generated by Django 3.1.1 on 2020-09-18 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('qr', models.CharField(max_length=999)),
                ('photo', models.ImageField(upload_to='photos')),
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
