# Generated by Django 3.1.1 on 2020-09-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200921_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
