# Generated by Django 3.1.1 on 2020-09-21 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0004_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('qr', models.CharField(blank=True, max_length=999, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
